site_name: Geotechnical Notes
repo_url: https://github.com/songzhenhe/geotechnical-note
site_author: 'songzhenhe'
copyright: '2020, songzhenhe'
theme: 
    # name: readthedocs
    # name: mkdocs
    name: material
    
markdown_extensions:
    - toc:
        permalink: true
    - pymdownx.arithmatex

extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
    
nav:
    - Home: index.md
    - Soil Mechanics:
      - Soil Classification: 01_soil_classification.md
      - Seepage: 02_seepage.md
      - Effective Stress: 03_effective_stress.md
      - Consolidation: 04_consolidation.md
      - Shear Strength: 05_shear_strength.md
      - Earth Pressure: 06_earth_pressure.md
    - Site Investigation:
      - Site Investigation: 11_site_investigation.md
      - Insitu Test: 12_insitu_test.md
      - Sampling: 13_sampling.md
    - Foundations:
      - Shallow Foundations: 21_shallow_foundations.md
      - Deep Foundations: 22_deep_foundations.md
    - Slope and Retaining Wall:
      - Slope: 31_slope.md
      - Retaining Wall: 32_retaining_wall.md
    - Numerical Modelling:
      - FLAC: 91_flac.md
#    - License: license.md

