site_name: Geotechnical Notes
repo_url: https://github.com/songzhenhe/geotechnical-note
site_author: 'songzhenhe'
copyright: '2020, songzhenhe'
theme: 
    # name: readthedocs
    # name: mkdocs
    name: material
    
markdown_extensions:
    - toc:
        permalink: true
    - pymdownx.arithmatex

extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
    
nav:
    - Home: index.md
    - Soil Mechanics:
      - Soil Classification: soil_mechanics/soil_classification.md
      - Seepage: soil_mechanics/seepage.md
      - Effective Stress: soil_mechanics/effective_stress.md
      - Shear Strength: soil_mechanics/shear_strength.md
      - Earth Pressure: soil_mechanics/earth_pressure.md
    - Site Investigation:
      - Site Investigation: site_investigation/site_investigation.md
      - Insitu Test: site_investigation/insitu_test.md
      - Sampling: site_investigation/sampling.md
    - Foundations:
      - Shallow Foundations: foundations/shallow_foundations.md
      - Deep Foundations: foundations/deep_foundations.md
    - Slope and Retaining Wall:
      - Slope: slope_retaining_wall/slope.md
      - Retaining Wall: slope_retaining_wall/retaining_wall.md
    - Numerical Modelling:
      - FLAC: numerical/flac.md
#    - Contributing: contributing.md
#    - License: license.md

